### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by wendao** [ISosnovik/nets#1]
I tried the code in Readme.md but only one layer in the picture.

**Comment by ISosnovik** [comment]
Seems like there sample code works fine while using Jupyter Notebook
Some errors may occur with TKinter-linked libs. 
However, it depends on the OS you use.

Thank you for using this micro framework.
I'll do my best, to make it work better with any OS and GUI realisation.

**Comment by wendao** [comment]
Great! Works fine on Jupyter, thank you!
